import { clazzArrayToMap } from "../../common/utils";

export const columns = clazzArrayToMap([
  { clazz: "columns-1", properties: "columns: 1;" },
  { clazz: "columns-2", properties: "columns: 2;" },
  { clazz: "columns-3", properties: "columns: 3;" },
  { clazz: "columns-4", properties: "columns: 4;" },
  { clazz: "columns-5", properties: "columns: 5;" },
  { clazz: "columns-6", properties: "columns: 6;" },
  { clazz: "columns-7", properties: "columns: 7;" },
  { clazz: "columns-8", properties: "columns: 8;" },
  { clazz: "columns-9", properties: "columns: 9;" },
  { clazz: "columns-10", properties: "columns: 10;" },
  { clazz: "columns-11", properties: "columns: 11;" },
  { clazz: "columns-12", properties: "columns: 12;" },
  { clazz: "columns-auto", properties: "columns: auto;" },
  { clazz: "columns-3xs", properties: "columns: 16rem;" },
  { clazz: "columns-2xs", properties: "columns: 18rem;" },
  { clazz: "columns-xs", properties: "columns: 20rem;" },
  { clazz: "columns-sm", properties: "columns: 24rem;" },
  { clazz: "columns-md", properties: "columns: 28rem;" },
  { clazz: "columns-lg", properties: "columns: 32rem;" },
  { clazz: "columns-xl", properties: "columns: 36rem;" },
  { clazz: "columns-2xl", properties: "columns: 42rem;" },
  { clazz: "columns-3xl", properties: "columns: 48rem;" },
  { clazz: "columns-4xl", properties: "columns: 56rem;" },
  { clazz: "columns-5xl", properties: "columns: 64rem;" },
  { clazz: "columns-6xl", properties: "columns: 72rem;" },
  { clazz: "columns-7xl", properties: "columns: 80rem;" },
]);
