import { clazzArrayToMap } from "../../common/utils";

export const columns = clazzArrayToMap([
  { clazz: "columns-1", properties: [{ value: "columns: 1;" }] },
  { clazz: "columns-2", properties: [{ value: "columns: 2;" }] },
  { clazz: "columns-3", properties: [{ value: "columns: 3;" }] },
  { clazz: "columns-4", properties: [{ value: "columns: 4;" }] },
  { clazz: "columns-5", properties: [{ value: "columns: 5;" }] },
  { clazz: "columns-6", properties: [{ value: "columns: 6;" }] },
  { clazz: "columns-7", properties: [{ value: "columns: 7;" }] },
  { clazz: "columns-8", properties: [{ value: "columns: 8;" }] },
  { clazz: "columns-9", properties: [{ value: "columns: 9;" }] },
  { clazz: "columns-10", properties: [{ value: "columns: 10;" }] },
  { clazz: "columns-11", properties: [{ value: "columns: 11;" }] },
  { clazz: "columns-12", properties: [{ value: "columns: 12;" }] },
  { clazz: "columns-auto", properties: [{ value: "columns: auto;" }] },
  { clazz: "columns-3xs", properties: [{ value: "columns: 16rem;" }] },
  { clazz: "columns-2xs", properties: [{ value: "columns: 18rem;" }] },
  { clazz: "columns-xs", properties: [{ value: "columns: 20rem;" }] },
  { clazz: "columns-sm", properties: [{ value: "columns: 24rem;" }] },
  { clazz: "columns-md", properties: [{ value: "columns: 28rem;" }] },
  { clazz: "columns-lg", properties: [{ value: "columns: 32rem;" }] },
  { clazz: "columns-xl", properties: [{ value: "columns: 36rem;" }] },
  { clazz: "columns-2xl", properties: [{ value: "columns: 42rem;" }] },
  { clazz: "columns-3xl", properties: [{ value: "columns: 48rem;" }] },
  { clazz: "columns-4xl", properties: [{ value: "columns: 56rem;" }] },
  { clazz: "columns-5xl", properties: [{ value: "columns: 64rem;" }] },
  { clazz: "columns-6xl", properties: [{ value: "columns: 72rem;" }] },
  { clazz: "columns-7xl", properties: [{ value: "columns: 80rem;" }] },
]);
