import { clazzArrayToMap } from "../../common/utils";

export const topRightBottomLeft = clazzArrayToMap([
  { clazz: "inset-0", properties: "inset: 0px;" },
  { clazz: "inset-x-0", properties: "left: 0px; right: 0px;" },
  { clazz: "inset-y-0", properties: "top: 0px; bottom: 0px;" },
  { clazz: "start-0", properties: "inset-inline-start: 0px;" },
  { clazz: "end-0", properties: "inset-inline-end: 0px;" },
  { clazz: "top-0", properties: "top: 0px;" },
  { clazz: "right-0", properties: "right: 0px;" },
  { clazz: "bottom-0", properties: "bottom: 0px;" },
  { clazz: "left-0", properties: "left: 0px;" },
  { clazz: "inset-px", properties: "inset: 1px;" },
  { clazz: "inset-x-px", properties: "left: 1px; right: 1px;" },
  { clazz: "inset-y-px", properties: "top: 1px; bottom: 1px;" },
  { clazz: "start-px", properties: "inset-inline-start: 1px;" },
  { clazz: "end-px", properties: "inset-inline-end: 1px;" },
  { clazz: "top-px", properties: "top: 1px;" },
  { clazz: "right-px", properties: "right: 1px;" },
  { clazz: "bottom-px", properties: "bottom: 1px;" },
  { clazz: "left-px", properties: "left: 1px;" },
  { clazz: "inset-0.5", properties: "inset: 0.125rem;" },
  { clazz: "inset-x-0.5", properties: "left: 0.125rem; right: 0.125rem;" },
  { clazz: "inset-y-0.5", properties: "top: 0.125rem; bottom: 0.125rem;" },
  { clazz: "start-0.5", properties: "inset-inline-start: 0.125rem;" },
  { clazz: "end-0.5", properties: "inset-inline-end: 0.125rem;" },
  { clazz: "top-0.5", properties: "top: 0.125rem;" },
  { clazz: "right-0.5", properties: "right: 0.125rem;" },
  { clazz: "bottom-0.5", properties: "bottom: 0.125rem;" },
  { clazz: "left-0.5", properties: "left: 0.125rem;" },
  { clazz: "inset-1", properties: "inset: 0.25rem;" },
  { clazz: "inset-x-1", properties: "left: 0.25rem; right: 0.25rem;" },
  { clazz: "inset-y-1", properties: "top: 0.25rem; bottom: 0.25rem;" },
  { clazz: "start-1", properties: "inset-inline-start: 0.25rem;" },
  { clazz: "end-1", properties: "inset-inline-end: 0.25rem;" },
  { clazz: "top-1", properties: "top: 0.25rem;" },
  { clazz: "right-1", properties: "right: 0.25rem;" },
  { clazz: "bottom-1", properties: "bottom: 0.25rem;" },
  { clazz: "left-1", properties: "left: 0.25rem;" },
  { clazz: "inset-1.5", properties: "inset: 0.375rem;" },
  { clazz: "inset-x-1.5", properties: "left: 0.375rem; right: 0.375rem;" },
  { clazz: "inset-y-1.5", properties: "top: 0.375rem; bottom: 0.375rem;" },
  { clazz: "start-1.5", properties: "inset-inline-start: 0.375rem;" },
  { clazz: "end-1.5", properties: "inset-inline-end: 0.375rem;" },
  { clazz: "top-1.5", properties: "top: 0.375rem;" },
  { clazz: "right-1.5", properties: "right: 0.375rem;" },
  { clazz: "bottom-1.5", properties: "bottom: 0.375rem;" },
  { clazz: "left-1.5", properties: "left: 0.375rem;" },
  { clazz: "inset-2", properties: "inset: 0.5rem;" },
  { clazz: "inset-x-2", properties: "left: 0.5rem; right: 0.5rem;" },
  { clazz: "inset-y-2", properties: "top: 0.5rem; bottom: 0.5rem;" },
  { clazz: "start-2", properties: "inset-inline-start: 0.5rem;" },
  { clazz: "end-2", properties: "inset-inline-end: 0.5rem;" },
  { clazz: "top-2", properties: "top: 0.5rem;" },
  { clazz: "right-2", properties: "right: 0.5rem;" },
  { clazz: "bottom-2", properties: "bottom: 0.5rem;" },
  { clazz: "left-2", properties: "left: 0.5rem;" },
  { clazz: "inset-2.5", properties: "inset: 0.625rem;" },
  { clazz: "inset-x-2.5", properties: "left: 0.625rem; right: 0.625rem;" },
  { clazz: "inset-y-2.5", properties: "top: 0.625rem; bottom: 0.625rem;" },
  { clazz: "start-2.5", properties: "inset-inline-start: 0.625rem;" },
  { clazz: "end-2.5", properties: "inset-inline-end: 0.625rem;" },
  { clazz: "top-2.5", properties: "top: 0.625rem;" },
  { clazz: "right-2.5", properties: "right: 0.625rem;" },
  { clazz: "bottom-2.5", properties: "bottom: 0.625rem;" },
  { clazz: "left-2.5", properties: "left: 0.625rem;" },
  { clazz: "inset-3", properties: "inset: 0.75rem;" },
  { clazz: "inset-x-3", properties: "left: 0.75rem; right: 0.75rem;" },
  { clazz: "inset-y-3", properties: "top: 0.75rem; bottom: 0.75rem;" },
  { clazz: "start-3", properties: "inset-inline-start: 0.75rem;" },
  { clazz: "end-3", properties: "inset-inline-end: 0.75rem;" },
  { clazz: "top-3", properties: "top: 0.75rem;" },
  { clazz: "right-3", properties: "right: 0.75rem;" },
  { clazz: "bottom-3", properties: "bottom: 0.75rem;" },
  { clazz: "left-3", properties: "left: 0.75rem;" },
  { clazz: "inset-3.5", properties: "inset: 0.875rem;" },
  { clazz: "inset-x-3.5", properties: "left: 0.875rem; right: 0.875rem;" },
  { clazz: "inset-y-3.5", properties: "top: 0.875rem; bottom: 0.875rem;" },
  { clazz: "start-3.5", properties: "inset-inline-start: 0.875rem;" },
  { clazz: "end-3.5", properties: "inset-inline-end: 0.875rem;" },
  { clazz: "top-3.5", properties: "top: 0.875rem;" },
  { clazz: "right-3.5", properties: "right: 0.875rem;" },
  { clazz: "bottom-3.5", properties: "bottom: 0.875rem;" },
  { clazz: "left-3.5", properties: "left: 0.875rem;" },
  { clazz: "inset-4", properties: "inset: 1rem;" },
  { clazz: "inset-x-4", properties: "left: 1rem; right: 1rem;" },
  { clazz: "inset-y-4", properties: "top: 1rem; bottom: 1rem;" },
  { clazz: "start-4", properties: "inset-inline-start: 1rem;" },
  { clazz: "end-4", properties: "inset-inline-end: 1rem;" },
  { clazz: "top-4", properties: "top: 1rem;" },
  { clazz: "right-4", properties: "right: 1rem;" },
  { clazz: "bottom-4", properties: "bottom: 1rem;" },
  { clazz: "left-4", properties: "left: 1rem;" },
  { clazz: "inset-5", properties: "inset: 1.25rem;" },
  { clazz: "inset-x-5", properties: "left: 1.25rem; right: 1.25rem;" },
  { clazz: "inset-y-5", properties: "top: 1.25rem; bottom: 1.25rem;" },
  { clazz: "start-5", properties: "inset-inline-start: 1.25rem;" },
  { clazz: "end-5", properties: "inset-inline-end: 1.25rem;" },
  { clazz: "top-5", properties: "top: 1.25rem;" },
  { clazz: "right-5", properties: "right: 1.25rem;" },
  { clazz: "bottom-5", properties: "bottom: 1.25rem;" },
  { clazz: "left-5", properties: "left: 1.25rem;" },
  { clazz: "inset-6", properties: "inset: 1.5rem;" },
  { clazz: "inset-x-6", properties: "left: 1.5rem; right: 1.5rem;" },
  { clazz: "inset-y-6", properties: "top: 1.5rem; bottom: 1.5rem;" },
  { clazz: "start-6", properties: "inset-inline-start: 1.5rem;" },
  { clazz: "end-6", properties: "inset-inline-end: 1.5rem;" },
  { clazz: "top-6", properties: "top: 1.5rem;" },
  { clazz: "right-6", properties: "right: 1.5rem;" },
  { clazz: "bottom-6", properties: "bottom: 1.5rem;" },
  { clazz: "left-6", properties: "left: 1.5rem;" },
  { clazz: "inset-7", properties: "inset: 1.75rem;" },
  { clazz: "inset-x-7", properties: "left: 1.75rem; right: 1.75rem;" },
  { clazz: "inset-y-7", properties: "top: 1.75rem; bottom: 1.75rem;" },
  { clazz: "start-7", properties: "inset-inline-start: 1.75rem;" },
  { clazz: "end-7", properties: "inset-inline-end: 1.75rem;" },
  { clazz: "top-7", properties: "top: 1.75rem;" },
  { clazz: "right-7", properties: "right: 1.75rem;" },
  { clazz: "bottom-7", properties: "bottom: 1.75rem;" },
  { clazz: "left-7", properties: "left: 1.75rem;" },
  { clazz: "inset-8", properties: "inset: 2rem;" },
  { clazz: "inset-x-8", properties: "left: 2rem; right: 2rem;" },
  { clazz: "inset-y-8", properties: "top: 2rem; bottom: 2rem;" },
  { clazz: "start-8", properties: "inset-inline-start: 2rem;" },
  { clazz: "end-8", properties: "inset-inline-end: 2rem;" },
  { clazz: "top-8", properties: "top: 2rem;" },
  { clazz: "right-8", properties: "right: 2rem;" },
  { clazz: "bottom-8", properties: "bottom: 2rem;" },
  { clazz: "left-8", properties: "left: 2rem;" },
  { clazz: "inset-9", properties: "inset: 2.25rem;" },
  { clazz: "inset-x-9", properties: "left: 2.25rem; right: 2.25rem;" },
  { clazz: "inset-y-9", properties: "top: 2.25rem; bottom: 2.25rem;" },
  { clazz: "start-9", properties: "inset-inline-start: 2.25rem;" },
  { clazz: "end-9", properties: "inset-inline-end: 2.25rem;" },
  { clazz: "top-9", properties: "top: 2.25rem;" },
  { clazz: "right-9", properties: "right: 2.25rem;" },
  { clazz: "bottom-9", properties: "bottom: 2.25rem;" },
  { clazz: "left-9", properties: "left: 2.25rem;" },
  { clazz: "inset-10", properties: "inset: 2.5rem;" },
  { clazz: "inset-x-10", properties: "left: 2.5rem; right: 2.5rem;" },
  { clazz: "inset-y-10", properties: "top: 2.5rem; bottom: 2.5rem;" },
  { clazz: "start-10", properties: "inset-inline-start: 2.5rem;" },
  { clazz: "end-10", properties: "inset-inline-end: 2.5rem;" },
  { clazz: "top-10", properties: "top: 2.5rem;" },
  { clazz: "right-10", properties: "right: 2.5rem;" },
  { clazz: "bottom-10", properties: "bottom: 2.5rem;" },
  { clazz: "left-10", properties: "left: 2.5rem;" },
  { clazz: "inset-11", properties: "inset: 2.75rem;" },
  { clazz: "inset-x-11", properties: "left: 2.75rem; right: 2.75rem;" },
  { clazz: "inset-y-11", properties: "top: 2.75rem; bottom: 2.75rem;" },
  { clazz: "start-11", properties: "inset-inline-start: 2.75rem;" },
  { clazz: "end-11", properties: "inset-inline-end: 2.75rem;" },
  { clazz: "top-11", properties: "top: 2.75rem;" },
  { clazz: "right-11", properties: "right: 2.75rem;" },
  { clazz: "bottom-11", properties: "bottom: 2.75rem;" },
  { clazz: "left-11", properties: "left: 2.75rem;" },
  { clazz: "right-11", properties: "right: 2.75rem;" },
  { clazz: "bottom-11", properties: "bottom: 2.75rem;" },
  { clazz: "left-11", properties: "left: 2.75rem;" },
  { clazz: "inset-12", properties: "inset: 3rem;" },
  { clazz: "inset-x-12", properties: "left: 3rem; right: 3rem;" },
  { clazz: "inset-y-12", properties: "top: 3rem; bottom: 3rem;" },
  { clazz: "start-12", properties: "inset-inline-start: 3rem;" },
  { clazz: "end-12", properties: "inset-inline-end: 3rem;" },
  { clazz: "top-12", properties: "top: 3rem;" },
  { clazz: "right-12", properties: "right: 3rem;" },
  { clazz: "bottom-12", properties: "bottom: 3rem;" },
  { clazz: "left-12", properties: "left: 3rem;" },
  { clazz: "inset-14", properties: "inset: 3.5rem;" },
  { clazz: "inset-x-14", properties: "left: 3.5rem; right: 3.5rem;" },
  { clazz: "inset-y-14", properties: "top: 3.5rem; bottom: 3.5rem;" },
  { clazz: "start-14", properties: "inset-inline-start: 3.5rem;" },
  { clazz: "end-14", properties: "inset-inline-end: 3.5rem;" },
  { clazz: "top-14", properties: "top: 3.5rem;" },
  { clazz: "right-14", properties: "right: 3.5rem;" },
  { clazz: "bottom-14", properties: "bottom: 3.5rem;" },
  { clazz: "left-14", properties: "left: 3.5rem;" },
  { clazz: "inset-16", properties: "inset: 4rem;" },
  { clazz: "inset-x-16", properties: "left: 4rem; right: 4rem;" },
  { clazz: "inset-y-16", properties: "top: 4rem; bottom: 4rem;" },
  { clazz: "start-16", properties: "inset-inline-start: 4rem;" },
  { clazz: "end-16", properties: "inset-inline-end: 4rem;" },
  { clazz: "top-16", properties: "top: 4rem;" },
  { clazz: "right-16", properties: "right: 4rem;" },
  { clazz: "bottom-16", properties: "bottom: 4rem;" },
  { clazz: "left-16", properties: "left: 4rem;" },
  { clazz: "inset-20", properties: "inset: 5rem;" },
  { clazz: "inset-x-20", properties: "left: 5rem; right: 5rem;" },
  { clazz: "inset-y-20", properties: "top: 5rem; bottom: 5rem;" },
  { clazz: "start-20", properties: "inset-inline-start: 5rem;" },
  { clazz: "end-20", properties: "inset-inline-end: 5rem;" },
  { clazz: "top-20", properties: "top: 5rem;" },
  { clazz: "right-20", properties: "right: 5rem;" },
  { clazz: "bottom-20", properties: "bottom: 5rem;" },
  { clazz: "left-20", properties: "left: 5rem;" },
  { clazz: "inset-24", properties: "inset: 6rem;" },
  { clazz: "inset-x-24", properties: "left: 6rem; right: 6rem;" },
  { clazz: "inset-y-24", properties: "top: 6rem; bottom: 6rem;" },
  { clazz: "start-24", properties: "inset-inline-start: 6rem;" },
  { clazz: "end-24", properties: "inset-inline-end: 6rem;" },
  { clazz: "top-24", properties: "top: 6rem;" },
  { clazz: "right-24", properties: "right: 6rem;" },
  { clazz: "bottom-24", properties: "bottom: 6rem;" },
  { clazz: "left-24", properties: "left: 6rem;" },
  { clazz: "inset-28", properties: "inset: 7rem;" },
  { clazz: "inset-x-28", properties: "left: 7rem; right: 7rem;" },
  { clazz: "inset-y-28", properties: "top: 7rem; bottom: 7rem;" },
  { clazz: "start-28", properties: "inset-inline-start: 7rem;" },
  { clazz: "end-28", properties: "inset-inline-end: 7rem;" },
  { clazz: "top-28", properties: "top: 7rem;" },
  { clazz: "right-28", properties: "right: 7rem;" },
  { clazz: "bottom-28", properties: "bottom: 7rem;" },
  { clazz: "left-28", properties: "left: 7rem;" },
  { clazz: "inset-32", properties: "inset: 8rem;" },
  { clazz: "inset-x-32", properties: "left: 8rem; right: 8rem;" },
  { clazz: "inset-y-32", properties: "top: 8rem; bottom: 8rem;" },
  { clazz: "start-32", properties: "inset-inline-start: 8rem;" },
  { clazz: "end-32", properties: "inset-inline-end: 8rem;" },
  { clazz: "top-32", properties: "top: 8rem;" },
  { clazz: "right-32", properties: "right: 8rem;" },
  { clazz: "bottom-32", properties: "bottom: 8rem;" },
  { clazz: "left-32", properties: "left: 8rem;" },
  { clazz: "inset-36", properties: "inset: 9rem;" },
  { clazz: "inset-x-36", properties: "left: 9rem; right: 9rem;" },
  { clazz: "inset-y-36", properties: "top: 9rem; bottom: 9rem;" },
  { clazz: "start-36", properties: "inset-inline-start: 9rem;" },
  { clazz: "end-36", properties: "inset-inline-end: 9rem;" },
  { clazz: "top-36", properties: "top: 9rem;" },
  { clazz: "right-36", properties: "right: 9rem;" },
  { clazz: "bottom-36", properties: "bottom: 9rem;" },
  { clazz: "left-36", properties: "left: 9rem;" },
  { clazz: "inset-40", properties: "inset: 10rem;" },
  { clazz: "inset-x-40", properties: "left: 10rem; right: 10rem;" },
  { clazz: "inset-y-40", properties: "top: 10rem; bottom: 10rem;" },
  { clazz: "start-40", properties: "inset-inline-start: 10rem;" },
  { clazz: "end-40", properties: "inset-inline-end: 10rem;" },
  { clazz: "top-40", properties: "top: 10rem;" },
  { clazz: "right-40", properties: "right: 10rem;" },
  { clazz: "bottom-40", properties: "bottom: 10rem;" },
  { clazz: "left-40", properties: "left: 10rem;" },
  { clazz: "inset-44", properties: "inset: 11rem;" },
  { clazz: "inset-x-44", properties: "left: 11rem; right: 11rem;" },
  { clazz: "inset-y-44", properties: "top: 11rem; bottom: 11rem;" },
  { clazz: "start-44", properties: "inset-inline-start: 11rem;" },
  { clazz: "end-44", properties: "inset-inline-end: 11rem;" },
  { clazz: "top-44", properties: "top: 11rem;" },
  { clazz: "right-44", properties: "right: 11rem;" },
  { clazz: "bottom-44", properties: "bottom: 11rem;" },
  { clazz: "left-44", properties: "left: 11rem;" },
  { clazz: "inset-48", properties: "inset: 12rem;" },
  { clazz: "inset-x-48", properties: "left: 12rem; right: 12rem;" },
  { clazz: "inset-y-48", properties: "top: 12rem; bottom: 12rem;" },
  { clazz: "start-48", properties: "inset-inline-start: 12rem;" },
  { clazz: "end-48", properties: "inset-inline-end: 12rem;" },
  { clazz: "top-48", properties: "top: 12rem;" },
  { clazz: "right-48", properties: "right: 12rem;" },
  { clazz: "bottom-48", properties: "bottom: 12rem;" },
  { clazz: "left-48", properties: "left: 12rem;" },
  { clazz: "inset-52", properties: "inset: 13rem;" },
  { clazz: "inset-x-52", properties: "left: 13rem; right: 13rem;" },
  { clazz: "inset-y-52", properties: "top: 13rem; bottom: 13rem;" },
  { clazz: "start-52", properties: "inset-inline-start: 13rem;" },
  { clazz: "end-52", properties: "inset-inline-end: 13rem;" },
  { clazz: "top-52", properties: "top: 13rem;" },
  { clazz: "right-52", properties: "right: 13rem;" },
  { clazz: "bottom-52", properties: "bottom: 13rem;" },
  { clazz: "left-52", properties: "left: 13rem;" },
  { clazz: "inset-56", properties: "inset: 14rem;" },
  { clazz: "inset-x-56", properties: "left: 14rem; right: 14rem;" },
  { clazz: "inset-y-56", properties: "top: 14rem; bottom: 14rem;" },
  { clazz: "start-56", properties: "inset-inline-start: 14rem;" },
  { clazz: "end-56", properties: "inset-inline-end: 14rem;" },
  { clazz: "top-56", properties: "top: 14rem;" },
  { clazz: "right-56", properties: "right: 14rem;" },
  { clazz: "bottom-56", properties: "bottom: 14rem;" },
  { clazz: "left-56", properties: "left: 14rem;" },
  { clazz: "inset-60", properties: "inset: 15rem;" },
  { clazz: "inset-x-60", properties: "left: 15rem; right: 15rem;" },
  { clazz: "inset-y-60", properties: "top: 15rem; bottom: 15rem;" },
  { clazz: "start-60", properties: "inset-inline-start: 15rem;" },
  { clazz: "end-60", properties: "inset-inline-end: 15rem;" },
  { clazz: "top-60", properties: "top: 15rem;" },
  { clazz: "right-60", properties: "right: 15rem;" },
  { clazz: "bottom-60", properties: "bottom: 15rem;" },
  { clazz: "left-60", properties: "left: 15rem;" },
  { clazz: "inset-64", properties: "inset: 16rem;" },
  { clazz: "inset-x-64", properties: "left: 16rem; right: 16rem;" },
  { clazz: "inset-y-64", properties: "top: 16rem; bottom: 16rem;" },
  { clazz: "start-64", properties: "inset-inline-start: 16rem;" },
  { clazz: "end-64", properties: "inset-inline-end: 16rem;" },
  { clazz: "top-64", properties: "top: 16rem;" },
  { clazz: "right-64", properties: "right: 16rem;" },
  { clazz: "bottom-64", properties: "bottom: 16rem;" },
  { clazz: "left-64", properties: "left: 16rem;" },
  { clazz: "inset-72", properties: "inset: 18rem;" },
  { clazz: "inset-x-72", properties: "left: 18rem; right: 18rem;" },
  { clazz: "inset-y-72", properties: "top: 18rem; bottom: 18rem;" },
  { clazz: "start-72", properties: "inset-inline-start: 18rem;" },
  { clazz: "end-72", properties: "inset-inline-end: 18rem;" },
  { clazz: "top-72", properties: "top: 18rem;" },
  { clazz: "right-72", properties: "right: 18rem;" },
  { clazz: "bottom-72", properties: "bottom: 18rem;" },
  { clazz: "left-72", properties: "left: 18rem;" },
  { clazz: "inset-80", properties: "inset: 20rem;" },
  { clazz: "inset-x-80", properties: "left: 20rem; right: 20rem;" },
  { clazz: "inset-y-80", properties: "top: 20rem; bottom: 20rem;" },
  { clazz: "start-80", properties: "inset-inline-start: 20rem;" },
  { clazz: "end-80", properties: "inset-inline-end: 20rem;" },
  { clazz: "top-80", properties: "top: 20rem;" },
  { clazz: "right-80", properties: "right: 20rem;" },
  { clazz: "bottom-80", properties: "bottom: 20rem;" },
  { clazz: "left-80", properties: "left: 20rem;" },
  { clazz: "inset-96", properties: "inset: 24rem;" },
  { clazz: "inset-x-96", properties: "left: 24rem; right: 24rem;" },
  { clazz: "inset-y-96", properties: "top: 24rem; bottom: 24rem;" },
  { clazz: "start-96", properties: "inset-inline-start: 24rem;" },
  { clazz: "end-96", properties: "inset-inline-end: 24rem;" },
  { clazz: "top-96", properties: "top: 24rem;" },
  { clazz: "right-96", properties: "right: 24rem;" },
  { clazz: "bottom-96", properties: "bottom: 24rem;" },
  { clazz: "left-96", properties: "left: 24rem;" },
  { clazz: "inset-y-96", properties: "top: 24rem; bottom: 24rem;" },
  { clazz: "start-96", properties: "inset-inline-start: 24rem;" },
  { clazz: "end-96", properties: "inset-inline-end: 24rem;" },
  { clazz: "top-96", properties: "top: 24rem;" },
  { clazz: "right-96", properties: "right: 24rem;" },
  { clazz: "bottom-96", properties: "bottom: 24rem;" },
  { clazz: "left-96", properties: "left: 24rem;" },
  { clazz: "inset-auto", properties: "inset: auto;" },
  { clazz: "inset-1/2", properties: "inset: 50%;" },
  { clazz: "inset-1/3", properties: "inset: 33.333333%;" },
  { clazz: "inset-2/3", properties: "inset: 66.666667%;" },
  { clazz: "inset-1/4", properties: "inset: 25%;" },
  { clazz: "inset-2/4", properties: "inset: 50%;" },
  { clazz: "inset-3/4", properties: "inset: 75%;" },
  { clazz: "inset-full", properties: "inset: 100%;" },
  { clazz: "inset-x-auto", properties: "left: auto; right: auto;" },
  { clazz: "inset-x-1/2", properties: "left: 50%; right: 50%;" },
  { clazz: "inset-x-1/3", properties: "left: 33.333333%; right: 33.333333%;" },
  { clazz: "inset-x-2/3", properties: "left: 66.666667%; right: 66.666667%;" },
  { clazz: "inset-x-1/4", properties: "left: 25%; right: 25%;" },
  { clazz: "inset-x-2/4", properties: "left: 50%; right: 50%;" },
  { clazz: "inset-x-3/4", properties: "left: 75%; right: 75%;" },
  { clazz: "inset-x-full", properties: "left: 100%; right: 100%;" },
  { clazz: "inset-y-auto", properties: "top: auto; bottom: auto;" },
  { clazz: "inset-y-1/2", properties: "top: 50%; bottom: 50%;" },
  { clazz: "inset-y-1/3", properties: "top: 33.333333%; bottom: 33.333333%;" },
  { clazz: "inset-y-2/3", properties: "top: 66.666667%; bottom: 66.666667%;" },
  { clazz: "inset-y-1/4", properties: "top: 25%; bottom: 25%;" },
  { clazz: "inset-y-2/4", properties: "top: 50%; bottom: 50%;" },
  { clazz: "inset-y-3/4", properties: "top: 75%; bottom: 75%;" },
  { clazz: "inset-y-full", properties: "top: 100%; bottom: 100%;" },
  { clazz: "start-auto", properties: "inset-inline-start: auto;" },
  { clazz: "start-1/2", properties: "inset-inline-start: 50%;" },
  { clazz: "start-1/3", properties: "inset-inline-start: 33.333333%;" },
  { clazz: "start-2/3", properties: "inset-inline-start: 66.666667%;" },
  { clazz: "start-1/4", properties: "inset-inline-start: 25%;" },
  { clazz: "start-2/4", properties: "inset-inline-start: 50%;" },
  { clazz: "start-3/4", properties: "inset-inline-start: 75%;" },
  { clazz: "start-full", properties: "inset-inline-start: 100%;" },
  { clazz: "end-auto", properties: "inset-inline-end: auto;" },
  { clazz: "end-1/2", properties: "inset-inline-end: 50%;" },
  { clazz: "end-1/3", properties: "inset-inline-end: 33.333333%;" },
  { clazz: "end-2/3", properties: "inset-inline-end: 66.666667%;" },
  { clazz: "end-1/4", properties: "inset-inline-end: 25%;" },
  { clazz: "end-2/4", properties: "inset-inline-end: 50%;" },
  { clazz: "end-3/4", properties: "inset-inline-end: 75%;" },
  { clazz: "end-full", properties: "inset-inline-end: 100%;" },
  { clazz: "top-auto", properties: "top: auto;" },
  { clazz: "top-1/2", properties: "top: 50%;" },
  { clazz: "top-1/3", properties: "top: 33.333333%;" },
  { clazz: "top-2/3", properties: "top: 66.666667%;" },
  { clazz: "top-1/4", properties: "top: 25%;" },
  { clazz: "top-2/4", properties: "top: 50%;" },
  { clazz: "top-3/4", properties: "top: 75%;" },
  { clazz: "top-full", properties: "top: 100%;" },
  { clazz: "right-auto", properties: "right: auto;" },
  { clazz: "right-1/2", properties: "right: 50%;" },
  { clazz: "right-1/3", properties: "right: 33.333333%;" },
  { clazz: "right-2/3", properties: "right: 66.666667%;" },
  { clazz: "right-1/4", properties: "right: 25%;" },
  { clazz: "right-2/4", properties: "right: 50%;" },
  { clazz: "right-3/4", properties: "right: 75%;" },
  { clazz: "right-full", properties: "right: 100%;" },
  { clazz: "bottom-auto", properties: "bottom: auto;" },
  { clazz: "bottom-1/2", properties: "bottom: 50%;" },
  { clazz: "bottom-1/3", properties: "bottom: 33.333333%;" },
  { clazz: "bottom-2/3", properties: "bottom: 66.666667%;" },
  { clazz: "bottom-1/4", properties: "bottom: 25%;" },
  { clazz: "bottom-2/4", properties: "bottom: 50%;" },
  { clazz: "bottom-3/4", properties: "bottom: 75%;" },
  { clazz: "bottom-full", properties: "bottom: 100%;" },
  { clazz: "left-auto", properties: "left: auto;" },
  { clazz: "left-1/2", properties: "left: 50%;" },
  { clazz: "left-1/3", properties: "left: 33.333333%;" },
  { clazz: "left-2/3", properties: "left: 66.666667%;" },
  { clazz: "left-1/4", properties: "left: 25%;" },
  { clazz: "left-2/4", properties: "left: 50%;" },
  { clazz: "left-3/4", properties: "left: 75%;" },
  { clazz: "left-full", properties: "left: 100%;" },
]);
