import { clazzArrayToMap } from "../../common/utils";

export const gridColumnStartEnd = clazzArrayToMap([
  { clazz: "col-auto", properties: "grid-column: auto;" },
  { clazz: "col-span-1", properties: "grid-column: span 1 / span 1;" },
  { clazz: "col-span-2", properties: "grid-column: span 2 / span 2;" },
  { clazz: "col-span-3", properties: "grid-column: span 3 / span 3;" },
  { clazz: "col-span-4", properties: "grid-column: span 4 / span 4;" },
  { clazz: "col-span-5", properties: "grid-column: span 5 / span 5;" },
  { clazz: "col-span-6", properties: "grid-column: span 6 / span 6;" },
  { clazz: "col-span-7", properties: "grid-column: span 7 / span 7;" },
  { clazz: "col-span-8", properties: "grid-column: span 8 / span 8;" },
  { clazz: "col-span-9", properties: "grid-column: span 9 / span 9;" },
  { clazz: "col-span-10", properties: "grid-column: span 10 / span 10;" },
  { clazz: "col-span-11", properties: "grid-column: span 11 / span 11;" },
  { clazz: "col-span-12", properties: "grid-column: span 12 / span 12;" },
  { clazz: "col-span-full", properties: "grid-column: 1 / -1;" },
  { clazz: "col-start-1", properties: "grid-column-start: 1;" },
  { clazz: "col-start-2", properties: "grid-column-start: 2;" },
  { clazz: "col-start-3", properties: "grid-column-start: 3;" },
  { clazz: "col-start-4", properties: "grid-column-start: 4;" },
  { clazz: "col-start-5", properties: "grid-column-start: 5;" },
  { clazz: "col-start-6", properties: "grid-column-start: 6;" },
  { clazz: "col-start-7", properties: "grid-column-start: 7;" },
  { clazz: "col-start-8", properties: "grid-column-start: 8;" },
  { clazz: "col-start-9", properties: "grid-column-start: 9;" },
  { clazz: "col-start-10", properties: "grid-column-start: 10;" },
  { clazz: "col-start-11", properties: "grid-column-start: 11;" },
  { clazz: "col-start-12", properties: "grid-column-start: 12;" },
  { clazz: "col-start-13", properties: "grid-column-start: 13;" },
  { clazz: "col-start-auto", properties: "grid-column-start: auto;" },
  { clazz: "col-end-1", properties: "grid-column-end: 1;" },
  { clazz: "col-end-2", properties: "grid-column-end: 2;" },
  { clazz: "col-end-3", properties: "grid-column-end: 3;" },
  { clazz: "col-end-4", properties: "grid-column-end: 4;" },
  { clazz: "col-end-5", properties: "grid-column-end: 5;" },
  { clazz: "col-end-6", properties: "grid-column-end: 6;" },
  { clazz: "col-end-7", properties: "grid-column-end: 7;" },
  { clazz: "col-end-8", properties: "grid-column-end: 8;" },
  { clazz: "col-end-9", properties: "grid-column-end: 9;" },
  { clazz: "col-end-10", properties: "grid-column-end: 10;" },
  { clazz: "col-end-11", properties: "grid-column-end: 11;" },
  { clazz: "col-end-12", properties: "grid-column-end: 12;" },
  { clazz: "col-end-13", properties: "grid-column-end: 13;" },
  { clazz: "col-end-auto", properties: "grid-column-end: auto;" },
]);
