import { clazzArrayToMap } from "../../common/utils";

export const gridRowStartEnd = clazzArrayToMap([
  { clazz: "row-auto", properties: "grid-row: auto;" },
  { clazz: "row-span-1", properties: "grid-row: span 1 / span 1;" },
  { clazz: "row-span-2", properties: "grid-row: span 2 / span 2;" },
  { clazz: "row-span-3", properties: "grid-row: span 3 / span 3;" },
  { clazz: "row-span-4", properties: "grid-row: span 4 / span 4;" },
  { clazz: "row-span-5", properties: "grid-row: span 5 / span 5;" },
  { clazz: "row-span-6", properties: "grid-row: span 6 / span 6;" },
  { clazz: "row-span-7", properties: "grid-row: span 7 / span 7;" },
  { clazz: "row-span-8", properties: "grid-row: span 8 / span 8;" },
  { clazz: "row-span-9", properties: "grid-row: span 9 / span 9;" },
  { clazz: "row-span-10", properties: "grid-row: span 10 / span 10;" },
  { clazz: "row-span-11", properties: "grid-row: span 11 / span 11;" },
  { clazz: "row-span-12", properties: "grid-row: span 12 / span 12;" },
  { clazz: "row-span-full", properties: "grid-row: 1 / -1;" },
  { clazz: "row-start-1", properties: "grid-row-start: 1;" },
  { clazz: "row-start-2", properties: "grid-row-start: 2;" },
  { clazz: "row-start-3", properties: "grid-row-start: 3;" },
  { clazz: "row-start-4", properties: "grid-row-start: 4;" },
  { clazz: "row-start-5", properties: "grid-row-start: 5;" },
  { clazz: "row-start-6", properties: "grid-row-start: 6;" },
  { clazz: "row-start-7", properties: "grid-row-start: 7;" },
  { clazz: "row-start-8", properties: "grid-row-start: 8;" },
  { clazz: "row-start-9", properties: "grid-row-start: 9;" },
  { clazz: "row-start-10", properties: "grid-row-start: 10;" },
  { clazz: "row-start-11", properties: "grid-row-start: 11;" },
  { clazz: "row-start-12", properties: "grid-row-start: 12;" },
  { clazz: "row-start-13", properties: "grid-row-start: 13;" },
  { clazz: "row-start-auto", properties: "grid-row-start: auto;" },
  { clazz: "row-end-1", properties: "grid-row-end: 1;" },
  { clazz: "row-end-2", properties: "grid-row-end: 2;" },
  { clazz: "row-end-3", properties: "grid-row-end: 3;" },
  { clazz: "row-end-4", properties: "grid-row-end: 4;" },
  { clazz: "row-end-5", properties: "grid-row-end: 5;" },
  { clazz: "row-end-6", properties: "grid-row-end: 6;" },
  { clazz: "row-end-7", properties: "grid-row-end: 7;" },
  { clazz: "row-end-8", properties: "grid-row-end: 8;" },
  { clazz: "row-end-9", properties: "grid-row-end: 9;" },
  { clazz: "row-end-10", properties: "grid-row-end: 10;" },
  { clazz: "row-end-11", properties: "grid-row-end: 11;" },
  { clazz: "row-end-12", properties: "grid-row-end: 12;" },
  { clazz: "row-end-13", properties: "grid-row-end: 13;" },
  { clazz: "row-end-auto", properties: "grid-row-end: auto;" },
]);
